<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifiers>win-x64;linux-musl-x64</RuntimeIdentifiers>
    <Configurations>Debug;Release</Configurations>
    <Platforms>x64</Platforms>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.1.0" />
    <PackageReference Include="protobuf-net" Version="3.1.22" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Controllers\*.cs" />
    <Compile Include="Hubs\*.cs" />
    <Compile Include="Models\*.cs" />
    <Compile Include="Services\*.cs" />
    <Compile Include="Shared\**\*.cs" />
    <Compile Include="SignalR.Protobuf.Server\**\*.cs" Exclude="SignalR.Protobuf.Server\obj\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="files\" />
  </ItemGroup>

</Project>